Weapons
erikvader/vov pull request #118
Opened 2020-12-08 14:40 UTC by carle3

closing #107 #95

2020-12-08 15:15 UTC, erikvader requested changes

2020-12-08 15:15 UTC, erikvader commented on src/client/game.ts
> +  private stateNumber: number;
Detta sparas redan i `this.states.last` eller nåt sånt. Om detta är en siffra som ökar för varje state iaf.

2020-12-08 15:15 UTC, erikvader commented on src/client/game.ts
> +      ) {
nu pallar jag inte tänka, men behövs verkligen broadcast rate här? Behöver den inte bara kolla på state number? Kan ha fel

2020-12-08 15:15 UTC, erikvader commented on src/common/entity.ts
> +          new Enemy(id, health, position, obj['damage']),
`damage` borde inkluderas i `isObjectWIthKeys`

2020-12-08 15:15 UTC, erikvader commented on src/common/simulation.ts
> +    //this._stepCounter % Math.floor(1 / this.updateStep) === 0
vad är detta?

2020-12-08 15:15 UTC, erikvader commented on src/common/simulation.ts
> +      this.state.players[id].firing = true;
ta bort alla firing? Eller används det ens?

2020-12-08 15:15 UTC, erikvader commented on src/common/simulation.ts
> +      //  console.log('B: ', b.getType(), b.getBody().getPosition());
console.log("varför är detta här?");

2020-12-08 15:15 UTC, erikvader commented on src/server/serverSimulation.ts
> +      this.handlePlayerInput(body, idNum, input);
äre inte finare att ge den player på en gång? :)

2020-12-08 15:29 UTC, Dojlando commented on src/client/clientSimulation.ts
> +    //this.handlePlayerInput(body, input);
Ska den vara kvar eller inte? Bestäm er

2020-12-08 15:29 UTC, Dojlando commented on src/client/game.ts
> +      { x: x, y: y },
```suggestion
      { x, y },
```
Jag tror man kan skriva så där

2020-12-08 15:29 UTC, Dojlando commented on src/common/simulation.ts
> +    //this._stepCounter % Math.floor(1 / this.updateStep) === 0
Vad gör denna här?

2020-12-08 15:29 UTC, Dojlando commented on src/common/simulation.ts
> +    const mapHeight = this._gameMap.height * constants.TILE_LOGICAL_SIZE;
Bra variabelnamn!

2020-12-08 15:29 UTC, Dojlando commented on src/common/simulation.ts
> +      if (this._state.players[user_data_a?.id] !== undefined) {
samma sak som att skriva `if (this._state.players[user_data_a?.id])`

2020-12-08 15:29 UTC, Dojlando commented on src/common/simulation.ts
> +      if (this._state.players[user_data_b?.id] !== undefined) {
samma sak som `if (this._state.players[user_data_b?.id])`

2020-12-08 15:29 UTC, Dojlando commented on src/common/simulation.ts
> +      ) {
`if (enemy_id && player_id && this._state.enemies[enemy_id])`
Så kanske allt får plats på en rad och då blir Carl glad

2020-12-08 15:29 UTC, Dojlando commented on src/common/simulation.ts
> +      //  console.log('B: ', b.getType(), b.getBody().getPosition());
??

2020-12-08 15:30 UTC, carle3 commented on src/client/game.ts
> +      ) {
nej, skottet ska visas under ett  visst intervall

2020-12-08 15:40 UTC, ponterik requested changes

2020-12-08 15:40 UTC, ponterik commented on src/client/clientSimulation.ts
> +    //this.handlePlayerInput(body, input);
Varför är detta utkommenterat?

2020-12-08 15:40 UTC, ponterik commented on src/client/game.ts
> +    ) {
Borde inte player vara borttagen från ngn lista om hen är död?

2020-12-08 15:40 UTC, ponterik commented on src/common/simulation.ts
> +    const enemy_damage = 1; //Snälla Dark Vader, blunda när du ser detta. Det är tillfälligt och bör ändras om vi har olika typer av fiender...
Bör inte detta lägga i en const fil?

2020-12-08 15:40 UTC, ponterik commented on src/common/simulation.ts
> +      this.state.players[id].firing = true;
Det används väll clientside?

2020-12-08 15:40 UTC, ponterik commented on src/common/weapon.ts
> +  protected _weaponType: string;
Borde inte detta vara name och inte "weapon type".

2020-12-08 15:56 UTC, stan3984 commented on src/client/game.ts
> +          this.stateNumber + SERVER_BROADCAST_RATE
borde `3` vara i `constants.ts`?

2020-12-08 15:56 UTC, stan3984 commented on src/common/simulation.ts
> +    //this._stepCounter % Math.floor(1 / this.updateStep) === 0
varför finns den här?

2020-12-08 15:56 UTC, stan3984 commented on src/common/simulation.ts
> +      //  console.log('B: ', b.getType(), b.getBody().getPosition());
```suggestion
```

2020-12-08 15:56 UTC, stan3984 commented on src/client/clientSimulation.ts
> +    //this.handlePlayerInput(body, input);
ta bort?

2020-12-08 15:59 UTC, erikvader commented on src/client/clientSimulation.ts
> +    //this.handlePlayerInput(body, input);
det blir errors då

2020-12-09 10:13 UTC, carle3 commented on src/client/game.ts
> +    ) {
nope, döda players kommer ligga kvar i statet

2020-12-09 10:16 UTC, merged