Add readiness
erikvader/vov pull request #121
Opened 2020-12-09 15:43 UTC by stan3984

Closes #39 
Closes #112

2020-12-09 18:02 UTC, erikvader requested changes
- Är det inte onödigt att begära att det finns `PLAYER_LIMIT` med spelare nu? Vi kan ju nu göra så att det startar om alla anslutna spelare är redo. Då slipper vi ändra på ett hårdkodat värde hela tiden.
- Funkar det om spelare DC:ar innan spelet startar (pallar inte testa)? Det ser ut att göra det iaf, förutom på ett ställe! Någonstans säger vi ju vilket id alla enemies skall starta på. Den utgår just nu ifrån att `player_list` går från 0 till ett tal utan avbrott. Men om spelare DC:ar innan alla har tryckt ready så kommer `player_list` att innehålla hål typ, och då kommer enemy_id att börja på ett för litet tal. Så det skulle nog gå att "normalisera" alla idn i `player_list` innan spelet startar och innan servern berättar för alla klienter vilka idn de har.

2020-12-10 09:31 UTC, ponterik commented on public/index.html
> +    <button id="btn-ready">:-(</button>
.

2020-12-10 09:32 UTC, ponterik commented
> * Är det inte onödigt att begära att det finns `PLAYER_LIMIT` med spelare nu? Vi kan ju nu göra så att det startar om alla anslutna spelare är redo. Då slipper vi ändra på ett hårdkodat värde hela tiden.
> * Funkar det om spelare DC:ar innan spelet startar (pallar inte testa)? Det ser ut att göra det iaf, förutom på ett ställe! Någonstans säger vi ju vilket id alla enemies skall starta på. Den utgår just nu ifrån att `player_list` går från 0 till ett tal utan avbrott. Men om spelare DC:ar innan alla har tryckt ready så kommer `player_list` att innehålla hål typ, och då kommer enemy_id att börja på ett för litet tal. Så det skulle nog gå att "normalisera" alla idn i `player_list` innan spelet startar och innan servern berättar för alla klienter vilka idn de har.

Test

2020-12-10 10:55 UTC, aggeagge approved these changes

2020-12-10 10:56 UTC, erikvader approved these changes
https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif

2020-12-10 12:43 UTC, Dojlando approved these changes

2020-12-10 12:43 UTC, Dojlando commented on src/server/index.ts
> +  });
Ja, det här blev ju lite snyggare än det vi höll på med

2020-12-10 12:50 UTC, merged

2020-12-10 12:50 UTC, erikvader commented on src/server/index.ts
> +  });
https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif