fiketen pakon fi ärkon fi nukon findre mikon!
erikvader/vov pull request #140
Opened 2020-12-15 13:20 UTC by erikvader

Meddelandena från servern till klienten är typ en tredjedel så stora nu! Fler baby yodas!!
Nu används inte pson direkt, ett extra steg innan som heter `flatten` körs först.

Vi borde kunna ta bort alla revive då de har blivit ersatta utav explode.

2020-12-15 13:32 UTC, aggeagge approved these changes

2020-12-15 13:36 UTC, stan3984 requested changes

2020-12-15 13:36 UTC, stan3984 commented on src/common/misc.ts
> +    const ele = this.array.pop();
🤮
```suggestion
    const elem = this.array.pop();
```

2020-12-15 13:36 UTC, stan3984 commented on src/common/msg.ts
> +  const numacks = Object.values(stc.inputAck).length;
`numAcks` eller `num_acks`?

2020-12-15 13:41 UTC, Dojlando approved these changes
Ser bra ut, men om nu inte revive behövs, borde inte dem tas bort?

2020-12-15 15:03 UTC, erikvader commented
> Ser bra ut, men om nu inte revive behövs, borde inte dem tas bort?

jo!

2020-12-16 10:54 UTC, stan3984 approved these changes

2020-12-16 10:54 UTC, stan3984 commented on src/common/msg.ts
> +  const numacks = Object.values(stc.inputAck).length;
är ju inte ändrat

2020-12-16 13:31 UTC, merged