Create classes Entity, Enemy, Player
erikvader/vov pull request #32
Opened 2020-11-11 13:09 UTC by stan3984

2020-11-11 19:22 UTC, erikvader requested changes

2020-11-11 19:22 UTC, erikvader commented on src/common/misc.ts
> +export function interpolate(src: Vec2, dst: Vec2, delta: number): Vec2 {
ska det inte vara `(dst - src)*delta + src` ?

2020-11-11 19:22 UTC, erikvader commented on src/common/entity.ts
> +    this.velocity = velocity;
kommer velocity någonsin vara annat än 0 vid instansiering?

2020-11-11 19:22 UTC, erikvader commented on src/common/entity.ts
> +  // 'CircleShape' is not assignable to parameter of type 'Shape'
Låter weird, funkar här [TS Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoAs4AcUG8C+AUKJLIigMLBQIA2EG2KEAHpCACYDOamOyBQoXphkcAFzIqNeo34BeAfgDcQkcgSS5KRXFVA). Annars bestämmer den väl typen automatiskt? Behövs ens `any`?

2020-11-12 09:45 UTC, stan3984 commented on src/common/entity.ts
> +  // 'CircleShape' is not assignable to parameter of type 'Shape'
Jag har kanske missat något, men som det står så behövs `any` för att TypeScript ska vara nöjd, och ja, det är weird.

2020-11-12 11:14 UTC, erikvader requested changes

2020-11-12 11:14 UTC, erikvader commented on src/common/entity.ts
> +  // 'CircleShape' is not assignable to parameter of type 'Shape'
måste vara detta: https://github.com/shakiba/planck.js/issues/152
vi låter det vara tills dess

2020-11-12 11:14 UTC, erikvader commented on src/common/entity.ts
> +  getScore(): number {
ska vi inte använda https://www.typescriptlang.org/docs/handbook/classes.html#accessors ?

2020-11-12 11:17 UTC, stan3984 commented on src/common/entity.ts
> +  getScore(): number {
Vet inte, det är inget jag minns att vi har pratat om.

2020-11-12 13:10 UTC, Dojlando approved these changes

2020-11-12 13:10 UTC, aggeagge approved these changes

2020-11-12 13:15 UTC, erikvader approved these changes
Några getters är no-ops, men det spelar nog ingen större roll

2020-11-12 13:17 UTC, merged