added readme
erikvader/vov pull request #33
Opened 2020-11-11 15:40 UTC by Dojlando

2020-11-11 18:54 UTC, erikvader requested changes

2020-11-11 18:54 UTC, erikvader commented on README.md
> +Make sure to install prettier plugin to VS Code.
om man inte har just den editorn då? Och detta är väl inget krav?

2020-11-11 21:20 UTC, ponterik approved these changes
Väldigt uppskattat

2020-11-12 10:21 UTC, erikvader commented on README.md
> +Make sure to install prettier plugin to VS Code.
```suggestion
It is recommended to install a plugin for you editor that automatically runs prettier. See their [website](https://prettier.io/) for alternatives.
```

2020-11-12 12:10 UTC, merged