Game loop
erikvader/vov pull request #46
Opened 2020-11-13 12:49 UTC by erikvader

Create a cool game loop and integrate it into the already existing stuff.

Also made the networking behave like a lobby.

Closes #22

2020-11-13 17:43 UTC, ponterik commented on src/client/main.ts
> +  .load(() => {
Tycker vi borde ha kvar "setup" funktionen ist för att ha en anonym, men det är en smaksak.

2020-11-13 17:46 UTC, ponterik approved these changes
Se kommentaren för att lägga till en faktist funktion ist för att använda en anonym. Annars verkar det nice.

2020-11-15 10:48 UTC, stan3984 requested changes

2020-11-15 10:48 UTC, stan3984 commented on src/common/game-loop.ts
> +export default abstract class GameLoop {
Borde väl vara `/** ... */`, både här och på andra ställen? Skulle kanske vara bra med lite dokumentation på andra saker också, typ `ClientGame`.

2020-11-15 10:48 UTC, stan3984 commented on src/common/game-loop.ts
> +  }
Varför inte göra samma sak med `ups` och `fps` som med `maxUpdateStep`, eller vice versa?

2020-11-15 16:25 UTC, erikvader commented on src/common/game-loop.ts
> +export default abstract class GameLoop {
vad för sorts dokumentationssystem använder vi?

Och elakt att bara begära dokumentation utav mig :P Just `ClientGame` kommer nog ändras väldigt mycket, så den blir nog bara jobbig att dokumentera IMHO. `GameLoop` är ganska final hoppas jag, så därför fick den lite extra kärlek.

2020-11-15 16:28 UTC, erikvader commented on src/common/game-loop.ts
> +  }
Du har rätt, `maxUpdateStep` borde också vara ett argument.

Servern och klienten kanske vill ha olika värden, så därför passar argument bättre tycker jag.

2020-11-16 09:15 UTC, Dojlando commented
Kör du camelCase eller snake_case?

2020-11-16 09:30 UTC, stan3984 approved these changes

2020-11-16 09:33 UTC, erikvader commented
> Kör du camelCase eller snake_case?

Camel? Ser du inkosekvent användning eller varför frågar du?

2020-11-16 10:00 UTC, Dojlando approved these changes

2020-11-16 10:00 UTC, Dojlando commented on src/client/game.ts
> +  add_character(
snake_case

2020-11-16 10:00 UTC, Dojlando commented on src/client/game.ts
> +  key_presses(): void {
snake_case

2020-11-16 10:00 UTC, Dojlando commented on src/server/index.ts
> +  channel_id?: string;
snake_case

2020-11-16 10:00 UTC, Dojlando commented on src/server/index.ts
> +  const my_id = client_id;
snake_case

2020-11-16 10:00 UTC, Dojlando commented on src/server/index.ts
> +    player_id: my_id,
snake_case

2020-11-16 10:00 UTC, Dojlando commented on src/client/game.ts
> +  private player_list = {};
snake_case

2020-11-16 10:00 UTC, Dojlando commented on src/client/game.ts
> +  public my_id?: number;
snake_case

2020-11-16 10:00 UTC, Dojlando commented on src/client/game.ts
> +  private static readonly movement_speed = 2;
snake_case

2020-11-16 10:00 UTC, Dojlando commented on src/client/game.ts
> +    img_filepath: string,
snake_case

2020-11-16 10:02 UTC, aggeagge approved these changes

2020-11-16 10:35 UTC, carle3 approved these changes

2020-11-16 10:46 UTC, merged