Add class Tileset
erikvader/vov pull request #59
Opened 2020-11-16 14:29 UTC by stan3984

Map-klass kommer senare.

`.tsx` och `.tmx` verkar behövas trots allt, så de är tillbaka.

2020-11-16 15:15 UTC, stan3984 commented
Jag har inte lagt till kollisioner för tiles ännu, så merge:a inte.

2020-11-16 16:14 UTC, erikvader commented
https://github.com/erikvader/vov/blob/6741b2b3513934f7f6893a6f1f25e088bf988b34/webpack.config.js#L29

Testa ta bort `x?` så att det bara står `/\.ts$/`.

2020-11-17 01:12 UTC, ponterik approved these changes

2020-11-17 12:42 UTC, erikvader requested changes
Alla grejer du hämtar från `SpriteUtilities` är bara alias/omexporteringar från `PIXI`. Är nog bättre att hämta dem direkt därifrån istället.

2020-11-17 13:38 UTC, erikvader requested changes
ser bra ut med flaggan

2020-11-17 13:38 UTC, erikvader commented on src/client/tileset.ts
> +import SpriteUtilities from './spriteUtilities.js';
```suggestion
```

2020-11-17 13:38 UTC, erikvader commented on src/client/tileset.ts
> +      baseTexture = new su.Texture(su.TextureCache[texturePath]);
Du glömde denna

2020-11-17 13:38 UTC, erikvader commented on src/client/tileset.ts
> +  constructor(name: string, su: SpriteUtilities, loadTextures: boolean) {
```suggestion
  constructor(name: string, loadTextures: boolean) {
```

2020-11-17 14:54 UTC, erikvader approved these changes
sugoi!

2020-11-18 08:01 UTC, stan3984 commented
Stänger denna, samma saker plus lite extra finns i #62 .

2020-11-18 08:01 UTC, closed without merging