Add simulations
erikvader/vov pull request #69
Opened 2020-11-18 14:45 UTC by stan3984

Closes #64 .

2020-11-19 09:38 UTC, aggeagge approved these changes

2020-11-19 16:03 UTC, ponterik approved these changes

2020-11-20 09:50 UTC, aggeagge commented on src/common/entity.ts
>      throw new Error("coudln't revive Enemy");
coudln't

2020-11-20 10:00 UTC, carle3 commented on src/common/sim.ts
> +  const MOVE_FORCE_STRENGTH = 10;
konstantfilen?

2020-11-20 10:00 UTC, aggeagge approved these changes

2020-11-20 13:12 UTC, Dojlando approved these changes

2020-11-20 13:46 UTC, erikvader requested changes

2020-11-20 13:46 UTC, erikvader commented on src/client/client-sim.ts
> +  }
Du glömmer att lägga till och ta bort bodies som inte finns längre eller är nya.

2020-11-20 13:46 UTC, erikvader commented on src/common/constants.ts
> +export const PLAYER_MOVE_VELOCITY = 10;
Är detta samma sak som movement_speed?

2020-11-20 13:46 UTC, erikvader commented on src/common/entity.ts
> +  }
gömmer du inte att kopiera velocity?

2020-11-20 13:46 UTC, erikvader commented on src/common/entity.ts
> +      (' ' + this.name).slice(1), // https://stackoverflow.com/a/31733628
vi vill aldrig ändra på strängen ändå, så det är fine att inte kopiera.

2020-11-20 13:46 UTC, erikvader commented on src/common/entity.ts
> +  }
glömmer du inte att kopiera velocity?

2020-11-20 13:46 UTC, erikvader commented on src/server/server-sim.ts
> +    // update players based on their inputs
ska detta var en vanlig docstring kanske?

2020-11-20 13:46 UTC, erikvader commented on src/server/server-sim.ts
> +    // update our state
```c
// add one to a
int a = a + 1
```

2020-11-22 23:03 UTC, erikvader commented
Jag tycker fortfarande att strängen inte skall kopieras. Den sätts i början när lobbyn skapas och ändras aldrig. Med tanke på att den kommer att kopieras varje frame så känns det bara väldigt onödigt.

Är supernöjd annars!

2020-11-23 07:07 UTC, merged