Communication Reliability Feature
erikvader/vov pull request #71
Opened 2020-11-18 23:33 UTC by erikvader

Basically try to create reliable communication over UDP.

More precisely:
- Client sends redundant `Input`s
- Client prepares to rewind its predicted states and to ignore old state updates.
- Server handles redundant inputs in the correct order
- Maybe small buffering of inputs on the server??

Closes #63

2020-11-19 10:34 UTC, aggeagge commented on src/common/deque.ts
> + * value is added unto some kind of timeline kinda, annoying to explain.
... lite dåligt

2020-11-19 10:36 UTC, erikvader commented on src/common/deque.ts
> + * value is added unto some kind of timeline kinda, annoying to explain.
haha ja! Men reviewa inte än! Är inte ens klar! PR:en är ju markerad som en draft av en anledning

2020-11-19 10:38 UTC, aggeagge commented on src/common/deque.ts
> +  public pop_end(): T {
varför slutade du med first och last?

2020-11-19 10:38 UTC, aggeagge commented on src/common/deque.ts
> +  public pop_beg(): T {
Samma som tidigare kommentar, beg låter mycket skumt

2020-11-19 10:40 UTC, aggeagge commented on src/common/deque.ts
> +  public discard_beg_until(x: number): T | undefined {
beg? typ som kommentar som tidigare

2020-11-19 23:58 UTC, erikvader commented
This makes issue #74 more prominent. I plan to fix that one next.

2020-11-20 09:43 UTC, aggeagge approved these changes

2020-11-20 09:44 UTC, carle3 approved these changes

2020-11-20 10:01 UTC, stan3984 requested changes

2020-11-20 10:01 UTC, stan3984 commented on src/client/game.ts
>    private sprite_list = {};
Var konsekvent med snake_case eller camelCase

2020-11-20 10:01 UTC, stan3984 commented on src/common/deque.ts
> +  constructor(ind?: number) {
Kan man använda default-värden istället?

2020-11-20 10:01 UTC, stan3984 commented on src/common/deque.ts
> +  public first_ele(): T | undefined {
`ele` är ju bara 🤮
`first` eller `first_elem(ent)?`
samma på övriga ställen

2020-11-20 13:08 UTC, Dojlando commented on src/common/deque.ts
> +  public first_ele(): T | undefined {
Vad är ele för något?

2020-11-22 22:53 UTC, erikvader commented on src/client/game.ts
>    private sprite_list = {};
tror det är försent för oss att vara det vid det här laget :(

2020-11-22 22:53 UTC, erikvader commented on src/common/deque.ts
> +  constructor(ind?: number) {
säkert, blir väl ingen större skillnad?

2020-11-22 22:53 UTC, erikvader commented on src/common/deque.ts
> +  public first_ele(): T | undefined {
okej då :(

2020-11-23 07:11 UTC, stan3984 commented on src/common/deque.ts
> +  constructor(ind?: number) {
blir snyggare och lättare att följa vad som händer imo

2020-11-23 15:00 UTC, stan3984 approved these changes

2020-11-23 15:09 UTC, Dojlando approved these changes

2020-11-23 15:10 UTC, merged