Spawn enemies
erikvader/vov pull request #78
Opened 2020-11-20 14:10 UTC by carle3

2020-11-20 14:33 UTC, erikvader requested changes
sry för att jag är så elak :(

2020-11-20 14:33 UTC, erikvader commented on src/client/game.ts
> +  private enemy_list = {};
Finns det en nuvarande eller framtida anledning till att spara spritsen i olika object?

2020-11-20 14:33 UTC, erikvader commented on src/client/game.ts
> +  // this is not pretty
```suggestion
  
```
Äre inte onödigt att ha såna här kommentarer? Gör issues om det är ett riktigt problem tänker jag

2020-11-20 14:33 UTC, erikvader commented on src/client/game.ts
> +    }
Det blir jobbigt att synka `dead_enemies` och se till att alla som har dött faktiskt försvinner. Det blir svårt att spola tillbaka till ett tidigare state också om tänker jag.

2020-11-20 14:33 UTC, erikvader commented on src/common/entity.ts
> +
den här ska nog inte vara kvar i slutändan, men den borde använda `this._velocity` istället för `Vec2(0, 1)` i alla fall.

2020-11-20 14:33 UTC, erikvader commented on src/common/game-loop.ts
> +    this.fps = 1000.0 / (args?.fps ?? 60); //bad variable name
```suggestion
    this.fps = 1000.0 / (args?.fps ?? 60);
```
gör issue eller faktiskt fixa det istället elr nåt

2020-11-20 16:38 UTC, erikvader commented on src/client/game.ts
> +  // this is not pretty
eller till en `TODO: split this function into smaller sub-functions`

2020-11-23 15:27 UTC, stan3984 approved these changes

2020-11-23 15:27 UTC, stan3984 commented on src/client/game.ts
> +    }*/
ta bort?

2020-11-23 15:31 UTC, carle3 commented on src/client/game.ts
> +  private enemy_list = {};
tror det är nice

2020-11-24 10:15 UTC, merged