Integrate physics with the game logic
erikvader/vov pull request #81
Opened 2020-11-24 17:37 UTC by stan3984

Closes probably something

2020-11-24 19:03 UTC, Dojlando commented on src/common/sim.ts
> +    return circleBody(world, entity.position, entity.velocity, 16);
Borde 16 vara hårdkodat?

2020-11-24 19:03 UTC, Dojlando commented on src/common/sim.ts
> +    return circleBody(world, entity.position, entity.velocity, 16);
Borde 16 vara hårdkodat?

2020-11-24 19:03 UTC, Dojlando commented on src/common/sim.ts
> +      Vec2(PLAYER_SPAWN_X, PLAYER_SPAWN_Y),
kommer inte alla spelare att spawna på varandra?

2020-11-25 09:50 UTC, erikvader requested changes
map.ts rad 27: Äre inte dumt att den körs varje gång? Går det inte att förberäkna den och spara i en egen instansvariabel? Eller den ändras väl aldrig?

2020-11-25 09:50 UTC, erikvader commented on src/common/constants.ts
> +export const TILE_TARGET_SIZE = 64;
```suggestion
```
vad är detta?

2020-11-25 09:50 UTC, erikvader commented on src/common/sim.ts
> +} from './constants';
```suggestion
import * as constants from './constants';
```
så slipper vi importera allt ett för ett

2020-11-25 09:50 UTC, erikvader commented on src/common/sim.ts
> +      Vec2(PLAYER_SPAWN_X, PLAYER_SPAWN_Y),
borde det bli en annan issue? Eller hur ska de spawnas? Just nu kan de inte intersecta med varandra, så de spawnar inte på varandra

2020-11-25 09:50 UTC, erikvader commented on src/common/tileset.ts
> +    const tiles = new Array<Tile>();
![image](https://user-images.githubusercontent.com/25645489/100209918-b3580280-2f0a-11eb-8d08-b03229988ba7.png)
Sry att jag outar dig @Dojlando D:

2020-11-25 09:52 UTC, erikvader commented on src/common/constants.ts
> +
Dedikerade locations i framtiden kanske? #83

2020-11-25 09:55 UTC, Dojlando commented on src/common/sim.ts
> +      Vec2(PLAYER_SPAWN_X, PLAYER_SPAWN_Y),
Min tanke var mest att det är lite skumt att vi har en konstant som säger vart spelarna spawnar, men ja, det borde nog vara en egen issue

2020-11-25 09:55 UTC, stan3984 commented on src/common/constants.ts
> +export const TILE_TARGET_SIZE = 64;
din idé

2020-11-25 09:57 UTC, erikvader commented on src/client/game.ts
> +        // we should probably think of a better solution in the future
göra till en TODO kanske?

2020-11-25 10:00 UTC, erikvader approved these changes

2020-11-25 10:20 UTC, aggeagge approved these changes

2020-11-25 10:20 UTC, carle3 approved these changes

2020-11-25 11:55 UTC, ponterik approved these changes

2020-11-25 14:55 UTC, ponterik requested changes

2020-11-25 14:55 UTC, ponterik commented on src/common/sim.ts
Vi har redan en klass för att räkna ut vilket håll karaktären rör sig åt. Om du vill ändra logiken så ändra i den klassen.

2020-11-25 14:57 UTC, ponterik requested changes

2020-11-25 14:57 UTC, ponterik commented on src/common/sim.ts
> +  }
Vi har redan en utility fil för att räkna ut direktions från keys, jag tycker den här logiken bör ligga där.

2020-11-25 15:23 UTC, stan3984 commented on src/common/sim.ts
> +  }
Behövs den modulen längre? Nu har vi 6 rader kod för att gå omkring jämfört med 75 rader i den andra modulen. Känns som vi kan ta bort den just nu och kanske lägga till något liknande senare om vi vill lägga till rekyler eller liknande.

2020-11-25 19:21 UTC, merged