Pathfinding
erikvader/vov pull request #88
Opened 2020-11-26 14:10 UTC by aggeagge

2020-11-26 14:56 UTC, stan3984 approved these changes

2020-11-27 13:44 UTC, erikvader requested changes

2020-11-27 13:44 UTC, erikvader commented on src/common/gameMap.ts
> +      Math.round((position.y + 0.1) / this.tileset.tileHeight) - 1;
behövs 0.1? Blir jobbigt för mig sen

2020-11-27 13:44 UTC, erikvader commented on src/common/simulation.ts
> +    const position = Vec2(48, 48);
detta ersätts kanske med spawn regions antar jag?

2020-11-27 13:44 UTC, erikvader commented on src/common/simulation.ts
> +        nextMove.add(Vec2(0, 0));
```suggestion
    if (nextPosition.x > currentPosition.x) {
      if (nextPosition.y > currentPosition.y) {
        nextMove.x = 1;
        nextMove.y = 1;
      } else if (nextPosition.y < currentPosition.y) {
        nextMove.x = 1;
        nextMove.y = -1;
      } else {
        nextMove.x = 1;
        nextMove.y = 0;
      }
    } else if (nextPosition.x < currentPosition.x) {
      if (nextPosition.y > currentPosition.y) {
        nextMove.x = -1;
        nextMove.y = 1;
      } else if (nextPosition.y < currentPosition.y) {
        nextMove.x = -1;
        nextMove.y = -1;
      } else {
        nextMove.x = -1;
        nextMove.y = 0;
      }
    } else {
      if (nextPosition.y > currentPosition.y) {
        nextMove.x = 0;
        nextMove.y = 1;
      } else if (nextPosition.y < currentPosition.y) {
        nextMove.x = 0;
        nextMove.y = -1;
      } else {
        nextMove.x = 0;
        nextMove.y = 0;
```

2020-11-27 13:44 UTC, erikvader commented on src/server/serverSimulation.ts
> +//import Level from '../common/gameMap'; // alias to not conflict with a map collection
```suggestion
```

2020-11-27 13:59 UTC, carle3 commented on src/common/simulation.ts
> +    const position = Vec2(48, 48);
yes, tack vader

2020-11-30 09:33 UTC, merged