finally the baby yodas can be killed
erikvader/vov pull request #96
Opened 2020-11-30 16:16 UTC by aggeagge

2020-11-30 20:02 UTC, erikvader requested changes

2020-11-30 20:02 UTC, erikvader commented on src/common/simulation.ts
> +      if (enemy.health === 0) {
```suggestion
      if (!enemy.alive) {
```

2020-11-30 20:02 UTC, erikvader commented on src/common/simulation.ts
> +    this._state.enemies[userData.id].takeDamage(1);
https://en.wikipedia.org/wiki/Magic_number_(programming)

2020-11-30 20:02 UTC, erikvader commented on src/common/simulation.ts
> +    const enemy = new Enemy(this._enemyIdCounter, 1, position);
https://en.wikipedia.org/wiki/Magic_number_(programming)

2020-12-01 09:22 UTC, ponterik approved these changes

2020-12-01 10:38 UTC, stan3984 approved these changes

2020-12-01 10:48 UTC, Dojlando requested changes

2020-12-01 10:48 UTC, Dojlando commented on src/common/simulation.ts
> +    console.log(userData.id);
ta bort `console.log`

2020-12-01 11:22 UTC, erikvader approved these changes

2020-12-01 13:34 UTC, merged